version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - project_network
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -d postgres -c 'SELECT 1;'" ]
      interval: 10s
      timeout: 5s
      retries: 10


  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: ./entrypoint.sh
    volumes:
      - shared_data:/media
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure
    depends_on:
      - db
    networks:
      - project_network
    links:
      - db


  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - shared_data:/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - project_network

networks:
  project_network:

volumes:
  pg_data:
  shared_data:
